"""empty message

Revision ID: ed0ab295f774
Revises: fe697d4cd7f3
Create Date: 2023-09-11 13:29:45.539827

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ed0ab295f774'
down_revision = 'fe697d4cd7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.alter_column('dish_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.alter_column('ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dish_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
